name: TomeitoLib
main: xyz.acrylicstyle.tomeito_core.TomeitoLib
load: STARTUP
version: 0.6.6
#api-version: "1.13" # todo: maybe specify api-version?

commands:
  tlib:
    description: Root command of TomeitoLib.
    usage: /<command> [args]
    permission: tomeitolib.cmd
    aliases: ["tl","tomeitolib","tlib"]
