name: TomeitoLib
main: xyz.acrylicstyle.tomeito_core.TomeitoLib
load: STARTUP
version: 0.5.19

commands:
  tlib:
    description: Root command of TomeitoLib.
    usage: /<command> [args]
    permission: tomeitolib.cmd
    aliases: ["tl","tomeitolib","tomeitol"]
