name: TomeitoLib
main: xyz.acrylicstyle.tomeito_core.TomeitoLib
load: STARTUP
version: 1.0.0

commands:
  tlib:
    description: Root command of TomeitoLib.
    usage: /<command> [args]
    permission: tomeitolib.info
    aliases: ["tl","tomeitolib","tomeitol"]
